# Generated by Django 3.1.4 on 2020-12-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
