# Generated by Django 3.1.4 on 2020-12-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_auto_20201222_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='pay',
            field=models.IntegerField(),
        ),
    ]
