# Generated by Django 3.1.4 on 2020-12-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0003_auto_20201222_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile_no',
            field=models.CharField(max_length=11),
        ),
    ]
