# Generated by Django 3.1.4 on 2020-12-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0007_auto_20201223_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Employe',
        ),
    ]
